# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish package to Maven Central

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - id: install-secret-key
        name: Install gpg secret key
        run: cat <(echo -e "${{ secrets.ORG_GPG_PRIVATE_KEY }}") | gpg --batch --import
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to Maven Central Snapshot Repository
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: PASSPHRASE
      - name: Publish to Maven Central Repository
        run: mvn -Pproduction -Prelease-sign-artifacts -Pdeploy --no-transfer-progress --batch-mode -U clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.ORG_OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.ORG_OSSRH_PASSWORD }}
          PASSPHRASE: ${{ secrets.ORG_GPG_PASSPHRASE }}
